// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnBi7hN1v0Xc_JQDyKY1uCvf4tNiyNVM',
    appId: '1:235100149079:web:9d0685faa91b0b32f7da12',
    messagingSenderId: '235100149079',
    projectId: 'bustracking-75371',
    authDomain: 'bustracking-75371.firebaseapp.com',
    storageBucket: 'bustracking-75371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9KYgnOzVdz-RSB9Kyc1mVqZrJHLrilIM',
    appId: '1:235100149079:android:4c109b5d7eb4947bf7da12',
    messagingSenderId: '235100149079',
    projectId: 'bustracking-75371',
    storageBucket: 'bustracking-75371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5w2hFsUOzZDWzMcZxYp6DdC8PzfsG0Q',
    appId: '1:235100149079:ios:d817b3530748df5df7da12',
    messagingSenderId: '235100149079',
    projectId: 'bustracking-75371',
    storageBucket: 'bustracking-75371.appspot.com',
    iosClientId: '235100149079-0b89a2ha5h0v9vce5t7du9iis4k15cub.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5w2hFsUOzZDWzMcZxYp6DdC8PzfsG0Q',
    appId: '1:235100149079:ios:1deed59252104108f7da12',
    messagingSenderId: '235100149079',
    projectId: 'bustracking-75371',
    storageBucket: 'bustracking-75371.appspot.com',
    iosClientId: '235100149079-44spc6qlafa2e5jls3paickf49nbccp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
